### ISSUE TITLE
Error: altislife: No such node (altislife.IP)

### ISSUE THREAD

**Issue by Fzww** [SteezCram/extDB3#12]
Bonjour, 

Voilà lors de l'installation de extDB3 sur linux & Windows j'en reviens toujours à la même erreur celle du fichier ci-joint.
J'ai bien installé tout les dépendances qui sont préciser dans le wiki.

Cdt, Léo.
[22-56-41.log](https://github.com/SteezCram/extDB3/files/7444307/22-56-41.log)

**Comment by SteezCram** [comment]
Hello,

I need your config file.

**Comment by Fzww** [comment]
extDB3 conf : https://www.toptal.com/developers/hastebin/taseyefava.sql
server.cfg : https://www.toptal.com/developers/hastebin/vesifidodi.php

**Comment by SteezCram** [comment]
You need to change the `[Database]` by `[your database name]`.

**Comment by Fzww** [comment]
the name of the database is altislife

**Comment by Fzww** [comment]
![image](https://user-images.githubusercontent.com/26601254/139582437-f948f8bc-bacc-4043-8336-d9bb9fcb572c.png)

**Comment by Fzww** [comment]
or you say for this one : 
![image](https://user-images.githubusercontent.com/26601254/139582463-b08f2589-f8e4-4b35-b620-555c10c36790.png)
 ?

**Comment by SteezCram** [comment]
Yes, it's that.

**Comment by Fzww** [comment]
i have a last request if you can help me, i have this pb i want to install the 2 package (deb)
![image](https://user-images.githubusercontent.com/26601254/139584695-bd8987bf-cd8b-43be-8b3e-41e229e0d8f4.png)

and IG i have this error ?
![image](https://user-images.githubusercontent.com/26601254/139584713-61d7aae6-56ec-495a-b6e6-69316ce83b14.png)
BE is disable

**Comment by EddyWallace** [comment]
For your first problem may try adding the 32 architecture to your package manager with:
```
# dpkg --add-architecture i386
# apt update
```

But I don't see a point in it since the 2.0 release of ArmA 3 there is a 64-bit Linux server version.

For your second problem did you tried to run extdb as a servermod with the
```
-servermod=@extdb\;...
```
And there should be no problem with BE.
At least I didn't encountered one in  conjunction with extdb.

PS: Working as root is not a good idea, you should add a user with sudo privileges (I assume you are using Ubuntu).

If you need a good step by step guide, the official BIS Wiki has a page for you: [https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Instructions_.28Linux_o.2Fs.29](https://community.bistudio.com/wiki/Arma_3:_Dedicated_Server#Instructions_.28Linux_o.2Fs.29)
